//! Source-level docs generator for Komandan modules.
//!
//! Extracts the registered module list from `src/modules/core.rs`, then for
//! each module reads `src/modules/<name>.rs` and pulls out the `///` doc
//! comment on the entry point plus the best-effort set of option keys
//! referenced via `params.<field>`. Emits a Markdown reference to stdout.
//!
//! Run with:
//! `cargo run --example gen_module_docs > docs/modules.md`

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Entry point. Returns `Err(message)` only when the module registry
/// (`src/modules/core.rs`) cannot be read or parsed; per-module read failures
/// are reported inline in the generated document instead of aborting.
fn main() -> Result<(), String> {
    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let modules_dir = crate_root.join("src").join("modules");
    let core_path = modules_dir.join("core.rs");

    let core_src = fs::read_to_string(core_path.as_path())
        .map_err(|e| format!("failed to read {}: {e}", core_path.display()))?;

    let mut names = parse_core_imports(&core_src).ok_or_else(|| {
        "could not find `use super::{ ... }` import block in src/modules/core.rs".to_string()
    })?;
    names.sort();
    names.dedup();

    let count = names.len();
    let mut out = String::new();
    writeln!(out, "# Komandan module reference").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "Auto-generated by `cargo run --example gen_module_docs > docs/modules.md`."
    )
    .ok();
    writeln!(out, "Do not edit by hand.").ok();
    writeln!(out).ok();
    writeln!(out, "{count} modules.").ok();
    writeln!(out).ok();

    for name in &names {
        let anchor = github_anchor(name);
        writeln!(out, "- [{name}](#{anchor})").ok();
    }
    writeln!(out).ok();
    writeln!(out, "---").ok();
    writeln!(out).ok();

    let mut first = true;
    for name in &names {
        if !first {
            writeln!(out).ok();
            writeln!(out, "---").ok();
            writeln!(out).ok();
        }
        out.push_str(&render_section(&modules_dir, name));
        first = false;
    }

    print!("{out}");
    Ok(())
}

/// Parse the `use super::{ a, b, c }` import block in `core.rs` and return the
/// list of module identifiers. Returns `None` if the block cannot be located.
fn parse_core_imports(src: &str) -> Option<Vec<String>> {
    let key = "use super::{";
    let start = src.find(key)? + key.len();
    let rest = &src[start..];
    let end = rest.find('}')?;
    let inner = &rest[..end];
    let names = inner
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string)
        .collect();
    Some(names)
}

/// Extract the `///` doc-comment block immediately preceding the
/// `pub fn <fn_name>(` declaration. Joined into a single line.
fn extract_doc_comment(src: &str, fn_name: &str) -> String {
    let needle = format!("pub fn {fn_name}(");
    let lines: Vec<&str> = src.lines().collect();
    let mut doc: Vec<String> = Vec::new();
    for (i, line) in lines.iter().enumerate() {
        if line.trim_start().starts_with(&needle) {
            let mut j = i;
            while j > 0 {
                j -= 1;
                let prev = lines[j].trim_start();
                if let Some(rest) = prev.strip_prefix("///") {
                    let body = rest.strip_prefix(' ').unwrap_or(rest);
                    doc.push(body.to_string());
                } else {
                    break;
                }
            }
            doc.reverse();
            break;
        }
    }
    doc.join(" ").trim().to_string()
}

/// Scan `src` for occurrences of `params.<ident>` and return the unique
/// identifiers, sorted. Uses a hand-rolled scanner (no `regex` dependency).
///
/// Lua-side access (`self.params.cmd`, `params.foo`) yields the identifier
/// directly. For modules that read options on the Rust side via the mlua Table
/// API (`params.get::<T>("key")` / `params.set("key", ...)`) the identifier
/// would be the API method name, so instead the string-literal argument is
/// extracted as the real option key.
fn scan_params(src: &str) -> Vec<String> {
    let bytes = src.as_bytes();
    let mut set: BTreeSet<String> = BTreeSet::new();
    let mut i = 0usize;
    while i < src.len() {
        let Some(pos) = src[i..].find("params") else {
            break;
        };
        let abs = i + pos;
        let after = abs + "params".len();
        if after < bytes.len() && bytes[after] == b'.' {
            let start = after + 1;
            let mut j = start;
            while j < bytes.len() && (bytes[j].is_ascii_alphanumeric() || bytes[j] == b'_') {
                j += 1;
            }
            if j > start {
                let ident = &src[start..j];
                if ident == "get" || ident == "set" {
                    if let Some(key) = extract_string_arg(src, j) {
                        set.insert(key);
                    }
                } else {
                    set.insert(ident.to_string());
                }
            }
        }
        i = after;
    }
    set.into_iter().collect()
}

/// From position `from` (just past an identifier like `get`/`set`), try to
/// locate a string-literal argument. Skips whitespace, an optional `::<...>`
/// turbofish, an opening paren, then reads a `"..."` / `'...'` literal.
fn extract_string_arg(src: &str, from: usize) -> Option<String> {
    let bytes = src.as_bytes();
    let mut k = from;
    let ws = |k: usize, bytes: &[u8]| {
        let mut t = k;
        while t < bytes.len() && bytes[t].is_ascii_whitespace() {
            t += 1;
        }
        t
    };
    k = ws(k, bytes);
    // optional turbofish ::<...>
    if k + 1 < bytes.len() && bytes[k] == b':' && bytes[k + 1] == b':' {
        k += 2;
        if k < bytes.len() && bytes[k] == b'<' && src[k..].find('>').is_some() {
            k += src[k..].find('>')? + 1;
        }
    }
    k = ws(k, bytes);
    if k >= bytes.len() || bytes[k] != b'(' {
        return None;
    }
    k += 1;
    k = ws(k, bytes);
    if k >= bytes.len() || (bytes[k] != b'"' && bytes[k] != b'\'') {
        return None;
    }
    let quote = bytes[k];
    k += 1;
    let start = k;
    while k < bytes.len() && bytes[k] != quote {
        if bytes[k] == b'\\' {
            k += 1;
        }
        k += 1;
    }
    if k > start {
        Some(src[start..k].to_string())
    } else {
        None
    }
}

/// Render a GitHub-style anchor: lowercase, keep alphanumerics only
/// (so `postgresql_user` -> `postgresqluser`, matching GitHub's heading slug).
fn github_anchor(name: &str) -> String {
    name.to_ascii_lowercase()
        .chars()
        .filter(|c| c.is_alphanumeric())
        .collect()
}

/// Render the Markdown section for a single module. If the module source file
/// cannot be read, an inline note is emitted and execution continues.
fn render_section(modules_dir: &Path, name: &str) -> String {
    let rel = format!("src/modules/{name}.rs");
    let path = modules_dir.join(format!("{name}.rs"));
    let mut section = String::new();
    let _ = writeln!(section, "## {name}");
    let _ = writeln!(section);

    match fs::read_to_string(path.as_path()) {
        Ok(src) => {
            // Only scan the non-test portion of the file: the `#[cfg(test)]`
            // block uses mlua's `params.set(...)` / `params.get(...)` Table
            // API which are not module options and would pollute the list.
            let src = src.split("#[cfg(test)]").next().unwrap_or(&src);
            let doc = extract_doc_comment(src, name);
            if doc.is_empty() {
                section.push_str("_(no description)_");
            } else {
                let _ = write!(section, "_{doc}_");
            }
            let _ = writeln!(section);
            let _ = writeln!(section);
            let _ = writeln!(section, "**Source:** [`{rel}`](../{rel})");
            let _ = writeln!(section);
            let keys = scan_params(src);
            if keys.is_empty() {
                let _ = writeln!(section, "**Options read:** _(none detected)_");
            } else {
                let joined = keys
                    .iter()
                    .map(|k| format!("`{k}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    section,
                    "**Options read:** {joined} _(best-effort; extracted from \
                     `params.<field>` usage in source)_"
                );
            }
        }
        Err(e) => {
            let _ = writeln!(section, "_(could not read `{rel}`: {e})_");
            let _ = writeln!(section);
            let _ = writeln!(section, "**Source:** [`{rel}`](../{rel})");
        }
    }
    section
}
