#![doc = include_str!("../README.md")]
//! <!-- crate-level docs pulled from README.md; see that file for the prose -->
//! <!-- overview and the plugin authoring example.                          -->
//!
//! # Stability / versioning
//!
//! This is the **interface crate** for komandan's dynamic plugin system
//! (spec: `docs/PLUGIN_SYSTEM_SPEC.md`). It declares the types, traits, and
//! entry-symbol contract; it contains **no plugin-loading logic** and **no
//! unsafe code**. The loader lives in the host binary crate, confined to a
//! single audited module per spec §5.
//!
//! Every public item is documented. `cargo clippy --all-targets -- -D warnings`
//! is part of the CI gate, matching komandan's lint posture exactly.
//!
//! # `abi_stable` pin
//!
//! Built against `abi_stable = "=0.11.3"` (latest stable on crates.io at the
//! time of writing). Minor pinned exactly because `abi_stable`'s
//! layout-checker macros bake field-offset and discriminant constants into
//! generated code that must match between host and plugin compiles — a
//! patch bump is safe; a minor bump needs a deliberate review.

#![deny(unsafe_code)]
#![deny(
    clippy::pedantic,
    clippy::nursery,
    clippy::enum_glob_use,
    clippy::unwrap_used,
    clippy::expect_used
)]
// `missing_docs_in_private_items` would force docs on private items too; we
// only require docs on public items per AGENTS.md.
#![warn(missing_docs)]

// Re-export abi_stable's FFI-safe std collections and the sabi_trait
// prelude so plugins write `use komandan_plugin_abi::prelude::*;` and get
// everything they need without a second dependency. Pinning the re-export
// surface here means a future abi_stable bump is a one-file review.
pub use abi_stable::std_types::{
    RHashMap, RNone, ROk, ROption, RResult, RSome, RStr, RString, RVec,
};

// `RArc` / `RBox` are exposed at the crate root because they appear in
// public type aliases (`CoreApiRef`, `LoggerSinkBox`, `PluginBox`).
pub use abi_stable::std_types::{RArc, RBox};

// Re-export the `#[sabi_trait]` prelude so plugin authors do not need to
// depend on abi_stable directly to write `TD_Opaque`.
pub use abi_stable::sabi_trait::TD_Opaque;

// Trait-object type aliases generated by `#[sabi_trait]`. They live in
// their declaring modules but downstream wants them at the crate root.
pub use crate::traits::{CoreApi_TO, CoreApiRef, LoggerSink_TO, LoggerSinkBox, Plugin_TO};

// Sub-modules — all public surface re-exported.
pub mod context;
pub mod entry;
pub mod error;
pub mod handles;
pub mod traits;
pub mod types;

// Mirror types.
pub use crate::context::PluginContext;
pub use crate::entry::{ABI_VERSION, ENTRY_SYMBOL, PluginBox, PluginEntryFn};
pub use crate::error::{CoreError, PluginError};
pub use crate::handles::{ConnectionHandle, LuaHandle};
pub use crate::traits::{CoreApi, LoggerSink, Plugin};
pub use crate::types::{
    GlobalFlags, HostInfo, LogLevel, ModuleResult, PluginDescriptor, RValue, ReportStatus,
    TaskInput,
};

/// Convenience prelude.
///
/// Plugin authors write `use komandan_plugin_abi::prelude::*;` and get every
/// mirror type, every trait, every alias, and the `abi_stable` std collections
/// needed to implement a plugin.
pub mod prelude {
    pub use crate::{
        PluginContext,
        entry::{ABI_VERSION, ENTRY_SYMBOL, PluginBox, PluginEntryFn},
        error::{CoreError, PluginError},
        handles::{ConnectionHandle, LuaHandle},
        traits::{CoreApi, CoreApiRef, LoggerSink, LoggerSinkBox, Plugin},
        types::{
            GlobalFlags, HostInfo, LogLevel, ModuleResult, PluginDescriptor, RValue, ReportStatus,
            TaskInput,
        },
    };
    // abi_stable std types frequently needed when authoring a plugin.
    pub use abi_stable::sabi_trait::TD_Opaque;
    pub use abi_stable::std_types::{
        RHashMap, RNone, ROk, ROption, RResult, RSome, RStr, RString, RVec,
    };
}
