name: Build aarch64

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 0.1.0)'
        required: true

jobs:
  get_build_number:
    runs-on: ubuntu-22.04-arm
    outputs:
      build_number: ${{ steps.set_number.outputs.build_number }}
    steps:
      - name: Generate build number
        id: set_number
        run: |
          echo "build_number=$(( $GITHUB_RUN_NUMBER ))" >> $GITHUB_OUTPUT

  build-aarch64:
    needs: get_build_number
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Change Cargo.toml version
        run: |
          VERSION="${{ github.event.inputs.version }}-build${{ needs.get_build_number.outputs.build_number }}"
          sed -i "s/^version[ ]*=[ ]*\"[^\"]*\"/version = \"${VERSION}\"/" Cargo.toml
          echo "Updated version in Cargo.toml:"
          grep "^version" Cargo.toml

      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Create Release Tag
        run: |
          TAG="v${{ github.event.inputs.version }}-build${{ needs.get_build_number.outputs.build_number }}"
          echo "RELEASE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Zip artifact
        run: zip -j komandan_${{ env.RELEASE_TAG }}-linux-aarch64.zip target/aarch64-unknown-linux-gnu/release/komandan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-aarch64-artifact
          path: |
            komandan_${{ env.RELEASE_TAG }}-linux-aarch64.zip
