name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Zip artifact
        run: zip -j komandan_${{ github.ref_name }}-linux_x86_64.zip target/x86_64-unknown-linux-gnu/release/komandan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            komandan_${{ github.ref_name }}-linux_x86_64.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-x86_64]
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          artifacts: |
            komandan_${{ github.ref_name }}-linux_x86_64.zip
