name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Strip binary
        run: strip target/x86_64-unknown-linux-gnu/release/komandan

      - name: Zip artifact
        run: zip -j komandan_${{ github.ref_name }}-linux-x86_64.zip target/x86_64-unknown-linux-gnu/release/komandan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-x86_64-artifact
          path: |
            komandan_${{ github.ref_name }}-linux-x86_64.zip

  build-aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hahnavi/komandan

      - name: Add target aarch64-unknown-linux-gnu
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install aarch64-linux-gnu-gcc
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu

      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-gnu
      
      - name: Strip binary
        run: aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/komandan

      - name: Zip artifact
        run: zip -j komandan_${{ github.ref_name }}-linux-aarch64.zip target/aarch64-unknown-linux-gnu/release/komandan

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-aarch64-artifact
          path: |
            komandan_${{ github.ref_name }}-linux-aarch64.zip

  release:
    runs-on: ubuntu-22.04
    needs: [build-x86_64, build-aarch64]
    permissions:
      contents: write
    steps:
      - name: Download artifact x86_64
        uses: actions/download-artifact@v4
        with:
          name: build-x86_64-artifact

      - name: Download artifact aarch64
        uses: actions/download-artifact@v4
        with:
          name: build-aarch64-artifact

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          body: Release ${{ github.ref_name }}
          artifacts: |
            komandan_${{ github.ref_name }}-linux-x86_64.zip
            komandan_${{ github.ref_name }}-linux-aarch64.zip
